### ISSUE TITLE
Outdated NPM version

### ISSUE THREAD

**Issue by RXminuS** [JarvusInnovations/lapidus#10]
Just realised that the latest NPM package version and the master branch aren't aligned and there's significant changes & bugfixes between the 2 versions.

Would it be possible to push a new NPM version or at least make clear (with tags) which version is deployed?

**Comment by jmealo** [comment]
@RXminuS: Thank you for reporting this. I will push a new version now.

**Comment by jmealo** [comment]
@RXminuS: Things got jammed up at work. The latest version is pushed now. I have some work redoing this natively as well as a MySQL/PostgreSQL -> Redis plugin with four different caching strategies if you're interested. Thanks for opening the PR!
